name: Auto push
 
on: 
  workflow_dispatch:
  push: 
    branches: [ master ]
  schedule:
    - cron: 35 21 * * 4
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install subconverter #安装subconverter
      run: |
        curl -LO https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar xvf subconverter_linux64.tar.gz
        mv -f subconverter/subconverter subconverter/subconverter.exe
    - name: log push  #获得自动部署的时间
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Commit #上传到仓库
      run: |
        git config --global user.email AutoupdateRobot@email.com
        git config --global user.name AutoupdateRobot
        git add .
        git commit -m "update new push" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
